DZ1/DZ/DZ/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace="main")),
    path('',include('DZ2.urls',namespace="DZ2")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DZ1/DZ/DZ2/urls.py
from django.contrib import admin
from django.urls import path,include
from DZ2 import views

app_name="DZ2"
urlpatterns = [
    path('',views.orders, name='order'),
    path('orders',views.orders, name='orders'),
    path('profile',views.profile, name='profile'),
]

DZ1/DZ/main/urls.py
from django.urls import path
from main import views
app_name="main"
urlpatterns = [
  
    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    

]

DZ1/DZ/DZ2/models.py
from django.db import models

class Products(models.Model):
    name=models.CharField( max_length=150, unique=True
                          ,verbose_name="Названее")
    slug=models.SlugField(max_length=200,blank=True,unique=True,verbose_name="URL")
    discription=models.TextField(blank=True,null=True, verbose_name="Описание")
    price=models.DecimalField(default=0.00, max_digits=7, decimal_places=2,verbose_name="Цена")
    quantity=models.PositiveIntegerField(default=0,verbose_name="Количество")
    date_create=models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "Product"
        verbose_name="Товар"
        verbose_name_plural="Товары"
        ordering=("id",)


class Userss(models.Model):
    name=models.CharField( max_length=150, unique=True,verbose_name="Имя")
    email=models.EmailField(max_length=150,verbose_name="Email")
    phone_number=models.CharField( max_length=150, unique=True,verbose_name="Телефон")
    address=models.TextField(blank=True,null=True, verbose_name="Адрес")
    slug=models.SlugField(max_length=200,blank=True,unique=True,verbose_name="URL")
    date_create=models.DateField(auto_now_add=True)
    image=models.ImageField(upload_to="userss",blank=True,null=True, verbose_name="фото профиля")
    # date_create=models.DateField() 
    def __str__(self):
        return self.name

    class Meta:
        db_table = "Userss"
        verbose_name="Пользователь"
        verbose_name_plural="Пользователи"
        ordering=("id",)

class Orders(models.Model):
    user=models.ForeignKey(to=Userss, verbose_name=("Пользователь"), on_delete=models.CASCADE)
    product=models.ForeignKey(to=Products, verbose_name=("Товар"), on_delete=models.CASCADE)
    price=models.DecimalField(default=0.00, max_digits=7, decimal_places=2,verbose_name="Сумма заказа")
    # date_create=models.DateField(auto_now_add=True)
    date_create=models.DateField() 
    def __str__(self):
        return str(self.id)

    class Meta:
        db_table = "Order"
        verbose_name="Заказ"
        verbose_name_plural="Заказы"
        ordering=("id",)


# Поля модели «Клиент»:
# — имя клиента
# — электронная почта клиента
# — номер телефона клиента
# — адрес клиента
# — дата регистрации клиента

# Поля модели «Товар»:
# — название товара
# — описание товара
# — цена товара
# — количество товара
# — дата добавления товара

# Поля модели «Заказ»:
# — связь с моделью «Клиент», указывает на клиента, сделавшего заказ
# — связь с моделью «Товар», указывает на товары, входящие в заказ
# — общая сумма заказа
# — дата оформления заказа

DZ1/DZ/main/models.py
from django.db import models

# Create your models here.

DZ1/DZ/DZ2/forms.py
from django import forms
from DZ2.models import Userss
CHOICES= [
    ('year', 'Год'),
    ('month', 'Месяц'),
    ('week', 'Неделя'),
    ]
class UserForm(forms.Form):
    # sort= forms.CharField(label='sort', widget=forms.RadioSelect(choices=CHOICES))
    ...

class ProfileForm(forms.ModelForm):
    name=forms.CharField( max_length=150)
    email=forms.EmailField(max_length=150)
    phone_number=forms.CharField( max_length=150)
    address=forms.CharField()
    image=forms.ImageField(required=False)
    class Meta:
        model=Userss
        fields=(
            "name",
            "email",
            "phone_number",
            "address",
            "image",
            
        )

DZ1/DZ/DZ2/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from DZ2.models import Userss,Orders,Products
from DZ2.forms import UserForm, ProfileForm
import datetime as DT   
from django.db.models import Q


def orders (request, user_id=1):
    if request.method=='POST':
        today = DT.date.today()
        week_ago = today - DT.timedelta(days=7)
        month_ago = today - DT.timedelta(days=31)
     
        year_ago = today - DT.timedelta(days=365)
        
        form=UserForm(data=request.POST)
        radio=request.POST['radio']
        
        if radio=="month":
            orders=Orders.objects.filter(Q(user_id=user_id),Q(date_create__gte=month_ago)).select_related("product")
           
        elif radio=="year":
            orders=Orders.objects.filter(Q(user_id=user_id),Q(date_create__gte=year_ago)).select_related("product")
           
        else:
           
            orders=Orders.objects.filter(Q(user_id=user_id),Q(date_create__gte=week_ago)).select_related("product")
    else:
        orders=Orders.objects.all()       
   
    context={
        "orders": orders
    }
    return render(request,'DZ2/orders.html',context)

def profile(request, user_id=1):
    user=Userss.objects.get(pk=user_id)
    if request.method=='POST':
        form = ProfileForm(data=request.POST, instance=user ,files=request.FILES)
        if form.is_valid():
            form.save()
    else:       
        form=ProfileForm(instance=user)
    context={
        'form':form
    }

    return render(request, "DZ2/profile.html", context)

DZ1/DZ/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
import logging

logger=logging.getLogger(__name__)
# Create your views here.
def index (request):
    logger.info('index page accessed')
    return render(request,'main/index.html')
def about (request):
    logger.info('about page accessed')
    return render(request,'main/about.html')

DZ1/DZ/DZ2/templates/DZ2/orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> Заказы</h1>
    <form action="{% url 'DZ2:orders' %}" method="POST">
        {% csrf_token %}
        <label >Сортировать </label>
        <input type="radio" name="radio" value="week"  > За неделю<Br>
        <input type="radio" name="radio" value="month"> За месяц<Br>
        <input type="radio" name="radio" value="year"> За год<Br>
        <button type="submit">Показать</button>
      
    </form>
    
    {% for order in orders %}
        <p>{{order.id}} | {{order.product.name}} | {{order.product.discription}}
            | {{order.date_create}}
        </p>
        
    {% endfor %}
        
{% endblock content %}

DZ1/DZ/DZ2/templates/DZ2/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> Данные профиля</h1>
    <form action="{% url 'DZ2:profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>

      
    </form>
    
    {% endblock content %}
        
    
        

DZ1/DZ/main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> Информация о магазине</h1>
{% endblock content %}

DZ1/DZ/main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> Магазин</h1>
{% endblock content %}

DZ1/DZ/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{% static "styles/style.css" %}">
    <title>Document</title>
</head>
<body>
    <div class="basemenu" >
        <form class="btn-base-menu" action="{% url 'main:index' %}">
            <button class="menu">Главная</button>
        </form>
        <form class="btn-base-menu" action="{% url 'main:about' %}">
            <button class="menu">О нас</button>
        </form>
        <form class="btn-base-menu" action="{% url 'DZ2:orders' %}">
            <button class="menu">Заказы</button>
        </form>
        <form class="btn-base-menu" action="{% url 'DZ2:profile' %}">
            <button class="menu">Профиль</button>
        </form>

    </div>
    
        
        {% block content %}
            
        {% endblock content %}
</body>
</html>